In [3]:
import os
import pandas as pd
path0 = "Data/Crime - Pandas.csv"
metadata0 = pd.read_csv(path0)

In [4]:
metadata0

,Country,Rank,Year,Crime Index,Year.1,Unnamed: 5,Unnamed: 6,Unnamed: 7,Country.1,2015,...,2017,2017.1,2018,2018.1,2019,2019.1,2020,2020.1,Average,Average.1
0,South Sudan,1.0,2015.0,85.32,2015.0,NaN,NaN,NaN,NaN,Rank,...,Rank,Crime Index,Rank,Crime Index,Rank,Crime Index,Rank,Crime Index,Rank,Crime Index
1,Venezuela,2.0,2015.0,84.07,2015.0,NaN,NaN,NaN,South Sudan,1,...,4,78.18,NaN,NaN,NaN,NaN,NaN,NaN,2.3,81.6
2,Guatemala,3.0,2015.0,79.34,2015.0,NaN,NaN,NaN,Afghanistan,5,...,6,73.85,NaN,NaN,NaN,NaN,4,76.23,5,75.8
3,South Africa,4.0,2015.0,78.44,2015.0,NaN,NaN,NaN,Honduras,9,...,3,78.34,3,78.89,78.89,3,5,76.11,17.3,64.6
4,Afghanistan,5.0,2015.0,77.34,2015.0,NaN,NaN,NaN,Malaysia,15,...,18,64.75,15,63.05,63.05,15,27,58.84,25,56.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Japan,125.0,2020.0,20.66,2020.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
752,Georgia,126.0,2020.0,20.21,2020.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,United Arab Emirates,127.0,2020.0,15.70,2020.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
754,Taiwan,128.0,2020.0,15.65,2020.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
755,Qatar,129.0,2020.0,11.86,2020.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
metadata0.Country.unique()

array(['South Sudan', 'Venezuela', 'Guatemala', 'South Africa',
       'Afghanistan', 'Guyana', 'Nigeria', 'Trinidad And Tobago',
       'Honduras', 'Bahamas', 'Kenya', 'Jamaica', 'Mongolia', 'Yemen',
       'Malaysia', 'Papua New Guinea', 'Libya', 'El Salvador', 'Brazil',
       'Maldives', 'Angola', 'Dominican Republic', 'Puerto Rico',
       'Bolivia', 'Somalia', 'Kyrgyzstan', 'Cameroon', 'Bangladesh',
       'Costa Rica', 'Argentina', 'Haiti', 'Belize', 'Zimbabwe',
       'Tanzania', 'Pakistan', 'Mozambique', 'Egypt', 'Uganda',
       'Uzbekistan', 'Peru', 'Colombia', 'Syria', 'Namibia', 'Paraguay',
       'Iraq', 'Ecuador', 'Mexico', 'Vietnam', 'Lebanon', 'Algeria',
       'Russia', 'Iran', 'Panama', 'United States', 'Sri Lanka',
       'Myanmar', 'France', 'Moldova', 'Albania', 'Fiji', 'Ghana',
       'Ukraine', 'Nepal', 'Ireland', 'Mauritius', 'Morocco', 'Italy',
       'Indonesia', 'Uruguay', 'Botswana', 'Kosovo (Disputed Territory)',
       'Kazakhstan', 'India', 'Bosnia And Herzegovina', 'Jordan', 'Chile',
       'Barbados', 'Cambodia', 'Timor-Leste', 'Kuwait', 'Bulgaria',
       'Serbia', 'Philippines', 'Tunisia', 'Nicaragua', 'Australia',
       'Sweden', 'Belgium', 'United Kingdom', 'Hungary', 'China',
       'Zambia', 'Greece', 'Bermuda', 'Bahrain', 'New Zealand', 'Canada',
       'Latvia', 'Thailand', 'Lithuania', 'Turkey', 'Laos',
       'North Macedonia', 'Portugal', 'Luxembourg', 'Sudan', 'Azerbaijan',
       'Netherlands', 'Palestine', 'Ethiopia', 'Montenegro',
       'Saudi Arabia', 'Oman', 'Spain', 'Slovakia', 'Iceland', 'Poland',
       'Czech Republic', 'Cyprus', 'Norway', 'Belarus', 'Israel',
       'Brunei', 'Romania', 'Finland', 'Croatia', 'Armenia', 'Slovenia',
       'Germany', 'Estonia', 'Monaco', 'Switzerland', 'Austria', 'Malta',
       'Denmark', 'United Arab Emirates', 'Georgia', 'Taiwan', 'Qatar',
       'Japan', 'Hong Kong', 'Rwanda', 'Faroe Islands', 'South Korea',
       'Turkmenistan', 'Singapore', 'Isle Of Man', nan, 'Cuba'],
      dtype=object)

In [6]:
uniquecountries = ['South Sudan', 'Venezuela', 'Guatemala', 'South Africa',
       'Afghanistan', 'Guyana', 'Nigeria', 'Trinidad And Tobago',
       'Honduras', 'Bahamas', 'Kenya', 'Jamaica', 'Mongolia', 'Yemen',
       'Malaysia', 'Papua New Guinea', 'Libya', 'El Salvador', 'Brazil',
       'Maldives', 'Angola', 'Dominican Republic', 'Puerto Rico',
       'Bolivia', 'Somalia', 'Kyrgyzstan', 'Cameroon', 'Bangladesh',
       'Costa Rica', 'Argentina', 'Haiti', 'Belize', 'Zimbabwe',
       'Tanzania', 'Pakistan', 'Mozambique', 'Egypt', 'Uganda',
       'Uzbekistan', 'Peru', 'Colombia', 'Syria', 'Namibia', 'Paraguay',
       'Iraq', 'Ecuador', 'Mexico', 'Vietnam', 'Lebanon', 'Algeria',
       'Russia', 'Iran', 'Panama', 'United States', 'Sri Lanka',
       'Myanmar', 'France', 'Moldova', 'Albania', 'Fiji', 'Ghana',
       'Ukraine', 'Nepal', 'Ireland', 'Mauritius', 'Morocco', 'Italy',
       'Indonesia', 'Uruguay', 'Botswana', 'Kosovo (Disputed Territory)',
       'Kazakhstan', 'India', 'Bosnia And Herzegovina', 'Jordan', 'Chile',
       'Barbados', 'Cambodia', 'Timor-Leste', 'Kuwait', 'Bulgaria',
       'Serbia', 'Philippines', 'Tunisia', 'Nicaragua', 'Australia',
       'Sweden', 'Belgium', 'United Kingdom', 'Hungary', 'China',
       'Zambia', 'Greece', 'Bermuda', 'Bahrain', 'New Zealand', 'Canada',
       'Latvia', 'Thailand', 'Lithuania', 'Turkey', 'Laos',
       'North Macedonia', 'Portugal', 'Luxembourg', 'Sudan', 'Azerbaijan',
       'Netherlands', 'Palestine', 'Ethiopia', 'Montenegro',
       'Saudi Arabia', 'Oman', 'Spain', 'Slovakia', 'Iceland', 'Poland',
       'Czech Republic', 'Cyprus', 'Norway', 'Belarus', 'Israel',
       'Brunei', 'Romania', 'Finland', 'Croatia', 'Armenia', 'Slovenia',
       'Germany', 'Estonia', 'Monaco', 'Switzerland', 'Austria', 'Malta',
       'Denmark', 'United Arab Emirates', 'Georgia', 'Taiwan', 'Qatar',
       'Japan', 'Hong Kong', 'Rwanda', 'Faroe Islands', 'South Korea',
       'Turkmenistan', 'Singapore', 'Isle Of Man', 'Cuba']